### ISSUE TITLE
Unable to run the example code

### ISSUE THREAD

**Issue by ferrao** [ziyasal/hapijs-status-monitor#18]
```
/Users/ferrao/Dev/hapijs-status-monitor/examples/node_modules/hapijs-status-monitor/src/helpers/socket-io-init.js:4
let io;
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/ferrao/Dev/hapijs-status-monitor/examples/node_modules/hapijs-status-monitor/src/middleware-wrapper.js:5:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by danielbayerlein** [comment]
@ferrao Which version of 
* Node.js
* hapijs-status-monitor
do you use?

**Comment by ferrao** [comment]
I have tried it with v4.4.0,  v4.5.0 and v5.8.0

**Comment by danielbayerlein** [comment]
@ferrao I will add support for Node.js v4 and v5 ASAP. Thanks for the report!

**Comment by danielbayerlein** [comment]
Fixed with c3fa6d439e4a362ec997dc6a14a84b9ff9aaf55c.

**Comment by danielbayerlein** [comment]
@ferrao Please try again.

**Comment by ferrao** [comment]
The examples work great @danielbayerlein , thank you for the prompt assistance!
Unfortunately I am still unable to use it on my project as i am getting another issue, check #19 .

**Comment by danielbayerlein** [comment]
hapijs-status-monitor 0.5.0 published 🎉
